main/urls.py
from django.urls import path
from main.views import create_item_flutter, show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, add_amount, min_amount, remove_item, delete_item, get_item_json, add_item_ajax, delete_item_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_amount/<int:id>/', add_amount, name='add_amount'),
    path('min_amount/<int:id>/', min_amount, name='min_amount'),
    path('remove-item/<int:id>/', remove_item, name='remove_item'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete-item-ajax/<int:item_id>/', delete_item_ajax, name='delete_item_ajax'),
    path('create-item-flutter/', create_item_flutter, name='create_item_flutter'),
]

tugas_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout 
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    
    items_count = items.filter(amount__gt=0).count()
    
    context = {
        'name': request.user.username,
        'class': 'PBP D',
        'items': items,
        'item_count': items_count,  # Menambah item_count ke dalam konteks
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    # Hapus data
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
            
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def add_amount(request, id):
    item = Item.objects.get(pk = id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def min_amount(request, id):
    item = Item.objects.get(pk = id)
    if item.amount > 0:
        item.amount -= 1
        item.save()
    if item.amount == 0:
        item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def remove_item(request, id):
    if request.method == 'POST':
        item = Item.objects.filter(user=request.user, pk=id).first()
        if item:
            item.delete()
    return redirect('main:show_main')

def get_item_json(request):
    product_items = Item.objects.filter(user=request.user)
    data = serializers.serialize('json', product_items)
    return HttpResponse(data, content_type='application/json')

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, user=user)
        new_product.save()
        
        response_data = {
            'id': new_product.id,
            'name': new_product.name,
            'amount': new_product.amount,
            'description': new_product.description,
            'date_added': new_product.date_added.strftime("%Y-%m-%d %H:%M:%S")
        }


        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, item_id):
    if request.method == 'DELETE':
        item = Item.objects.get(id=item_id)
        item.delete()
        return HttpResponse({'status': 'DELETED'}, status=200)
  
@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white text-center">
                    <h2>Add New Item</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="Enter item name here">
                        </div>
                        <div class="form-group">
                            <label for="amount">Amount</label>
                            <input type="number" id="amount" name="amount" class="form-control" placeholder="Enter item amount here" min="0">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea id="description" name="description" class="form-control" rows="4" placeholder="Enter item description here"></textarea>
                        </div>
                        <div class="form-group text-center" style="margin-top: 15px;">
                            <button type="submit" class="btn btn-success">Add Item</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body, html {
        height: 100%;
        margin: 0;
        background-color: #f0f0f0;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .login-container {
        width: 50vw;
        height: 100vh
        max-width: 100%; 
        padding: 20px;
        border-radius: 10px;
        background-color: #ffffff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .card-header {
        font-size: 1.5em;
    }

</style>

<div class="login-container">
    <div class="card">
        <div class="card-header bg-primary text-white">Login</div>
        <div class="card-body">

            <div class="text-center mb-4"></div>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" placeholder="Username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                </div>
                <div class="form-group text-center" style="margin-top: 10px;">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}


<div class="container" style="min-height: 100vh; min-width: 100vw; padding: 70px;">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-primary text-white">Inventory Page</div>
                <div class="card-body">
                    <h5>Name:</h5>
                    <p>{{name}}</p>
                    <h5>Class:</h5>
                    <p>{{class}}</p>

                    <div id="item_card" class="row"></div>

                    <h5>Sesi terakhir login: {{ last_login }}</h5>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
                    <a href="{% url 'main:logout' %}" class="btn btn-danger">Logout</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json());
    }

    async function refreshItems() {
        const items = await getItems();
        const itemCard = document.getElementById("item_card");
        itemCard.innerHTML = ""; // Kosongkan elemen sebelum menambahkan kartu

        items.forEach((item) => {
            const card = document.createElement("div");
            card.className = "col-md-4 mb-3";

            card.innerHTML = `
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <p class="card-text">Amount: ${item.fields.amount}</p>
                        <p class="card-text">Description: ${item.fields.description}</p>
                        <p class="card-text">Date Added: ${item.fields.date_added}</p>
                        <div class="card-footer">
                            <a href="add_amount/${item.pk}" class="btn btn-success btn-sm">Tambah</a>
                            <a href="min_amount/${item.pk}" class="btn btn-warning btn-sm">Kurang</a>
                            <button data-id="${item.pk}" class="btn btn-danger btn-sm" onclick="deleteItem(this.getAttribute('data-id'))">Delete</button>
                        </div>
                    </div>
                </div>
            `;

            itemCard.appendChild(card);
        });
    }

    async function deleteItem(itemId) {
        const deleteUrl = `{% url 'main:delete_item_ajax' item_id=999 %}`.replace('999', itemId);
        console.log(itemId);
        try {
            const response = await fetch(deleteUrl, {
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            }).then(refreshItems)
            
        } catch (error) {
            console.error('Error:', error);
        }
    }

    function addItem() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems);

        document.getElementById("form").reset();
        return false;
    }

    document.getElementById("button_add").onclick = addItem;

    // Panggil refreshItems() saat halaman pertama kali dimuat
    refreshItems();
    
    
</script>



{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}

<style>
    body, html {
        height: 100%;
        margin: 0;
        background-color: #f0f0f0;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .card-header {
        font-size: 1.5em;
    }
    .alert-success {
        color: green;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-20">
            <div class="card">
                <div class="card-header bg-primary text-white">Register</div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'success' %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% else %}
                                <ul class="alert alert-danger">
                                    <li>{{ message }}</li>
                                </ul>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}